# Generated by Django 3.2.12 on 2024-03-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20240315_0527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color_code',
            field=models.CharField(max_length=20),
        ),
    ]
