# Generated by Django 3.2.12 on 2024-03-15 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_alter_colors_color_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='people',
            old_name='color_id',
            new_name='just_color',
        ),
    ]
