# Generated by Django 3.2.12 on 2024-03-20 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_rename_color_id_people_just_color'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='people',
            options={},
        ),
    ]
